#https://docs.spring.io/spring-boot/appendix/application-properties/index.html#appendix.application-properties.data
spring:
  application:
    name: libraryapi

  #Conexï¿½o
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  #JPA
  jpa:
    show-sql: true
    hibernate:
      ddl_auto: update # none, create, create-drop
    properties:
      hibernate.format_sql: true

